[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  DATABASE_URL = "postgresql://neondb_owner:npg_GPnTNBx0V7ZA@ep-dry-dew-a1gjtzo2-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
  JWT_SECRET = "your-secret-key-change-this-in-netlify-dashboard"

[dev]
  command = "npm run dev"
  port = 4321
  targetPort = 4321

[[edge_functions]]
  function = "entry"
  path = "/*"

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/me"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/posts/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/comments"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/comments/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
