services:
  - type: web
    name: ablog
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ablog-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PUBLIC_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: PUBLIC_CLOUDINARY_API_KEY
        sync: false
      - key: PUBLIC_CLOUDINARY_API_SECRET
        sync: false
      - key: PUBLIC_CLOUDINARY_UPLOAD_PRESET
        sync: false

databases:
  - name: ablog-db
    databaseName: ablog
    user: ablog_user
